version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"     # monthly
    # 可选：限制每次最多提几个 PR，防止刷屏
    open-pull-requests-limit: 20
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
