languageCode = "zh-Hans"
languageName = "简体中文"
languageDirection = "ltr"
weight = 1

title = "LeaFrock的博客"
copyright = "&copy; 2025 LeaFrock"

[params]
  dateFormat = "2006年1月2日"

  mainSections = ["articles"]
  description = "LeaFrock的文章"

[params.author]
  name = "LeaFrock"
  image = "img/author.jpg"
  headline = ""
  bio = ""
  links = [
    { zhihu = "https://www.zhihu.com/people/leafrock" },
  ]
