languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "LeaFrock's Blog"
copyright = "&copy; 2025 LeaFrock"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["articles"]
  description = "LeaFrock's articles."

[params.author]
  name = "LeaFrock"
  image = "img/author.jpg"
  headline = ""
  bio = ""
  links = [
    { zhihu = "https://www.zhihu.com/people/leafrock" },
  ]
